### ISSUE TITLE
Change to error message for no file chosen when checking addresses

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#100]
The error message should be changed for when a user does not select a file but clicks on "Check Addresses" on the batch side of the tool. It currently says the following:

Formatting error
**We've noticed the following errors:**

This file is not a csv.

Suggest changing the verbiage to "You initiated a search but did not select a file. Please select a file".

**Comment by debseidner** [comment]
@benguhin Please weigh in on what the error message should say. Thank you.

**Comment by benguhin** [comment]
How about 

> You have not selected a file. Use the "Select file" button to select the file with your addresses.
