### ISSUE TITLE
when selecting "download CSV template" in IE11, the values open in the browser

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#101]
we would prefer it to download as a file! is there a way to force that?

**Comment by awolfe76** [comment]
This is generally a server-side fix.

@marcesher @Scotchester - something we can do?

http://stackoverflow.com/questions/17968837/file-opens-instead-of-downloading-in-internet-explorer-in-a-href-link
http://stackoverflow.com/questions/27257336/downloading-a-dynamic-csv-in-internet-explorer

**Comment by marcesher** [comment]
Been a long time since I've coded, so this is 3 year old knowledge.

My understanding, last time I coded, was that you needed to point to a server-side endpoint which then set the appropriate headers to force the browser to download the file.

I'm not sure what's changed in the last few years or whether it's possible to set those headers on the file at the webserver level.

**Comment by Scotchester** [comment]
Yeah, setting the server-side headers is definitely preferable. @rosskarchner, can you assist?

**Comment by awolfe76** [comment]
Wait, I'm sorry.

The CSV in this case is generated dynamically based on one or more HTML tables. So I don't think server-side is an option here.

Researching some more to see what options we do have.

**Comment by Scotchester** [comment]
I don't _think_ it has to be set for individual filenames. I think we can set it for all `.csv` files.

**Comment by awolfe76** [comment]
But if the file doesn't ever exist on the server it wouldn't matter at all. Right?

**Comment by Scotchester** [comment]
Hmm... not sure. You might be right.

**Comment by awolfe76** [comment]
So, the dynamic CSV download seems to be ok.

There is however a static CSV file, **sitting on the server**, that instead of downloading opens a new tab in IE11 (as the title of this issue states). 

@rosskarchner - any help is appreciated.
