### ISSUE TITLE
make language clearer that the CSV template is mandatory

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#102]
and that you have to keep the headers

**Comment by benguhin** [comment]
possibly move the download link above the select file button

**Comment by benguhin** [comment]
Something like this should work - it adds "The file must use our CSV template." to the instructions and moves the download link above the "Select file" button:

![screen shot 2015-12-14 at 3 35 44 pm](https://cloud.githubusercontent.com/assets/6953063/11793271/971e299c-a278-11e5-9054-849a425a0869.png)

**Comment by debseidner** [comment]
Can we add "The file must use our CSV template provided here" instead? I think that will point someone to the file right there in case they don't see it.

**Comment by debseidner** [comment]
Also, can we add a link to the CSV template in the "How do I upload multiple addresses from my database?" Maybe we can make the words "Comma Separated Values (CSV) format" into a link to the template?
@benguhin Does that seem right?

**Comment by awolfe76** [comment]
With the new language the forms look like:
![forms](https://cloud.githubusercontent.com/assets/2932572/11819053/e88a1a76-a32b-11e5-9018-e36e460bf01b.png)

Its ok, just wanted to point it out.

**Comment by benguhin** [comment]
How about this:

> To check on more than one loan, upload a Comma Separated Values (CSV) file with addresses for up to 250 properties. The file must use our CSV template: [Download CSV template]()

**Comment by awolfe76** [comment]
@benguhin - and remove the link below, right?

**Comment by benguhin** [comment]
yes! :)
