### ISSUE TITLE
Clarify what to do next for "Address not identified" results

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#106]
- fix it if it's incomplete
- try the census tool
- use the county lists, other means necessary

**Comment by benguhin** [comment]
possibly clarify that we may have found the address but can't find the determination

**Comment by awolfe76** [comment]
This sounds like a content update, right?

> possibly clarify that we may have found the address but can't find the determination

Not sure what that is, right now if we find an address we say rural or not.

**Comment by benguhin** [comment]
Yes, definitely content.

**Comment by benguhin** [comment]
@debseidner do you have a recommendation for how we should change the text on the results page?
