### ISSUE TITLE
consider changing button text

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#108]
"Check addresses" wasn't totally clear to our first test participant

**Comment by benguhin** [comment]
I'm ok with changing to "Submit addresses" if y'alls think that that's clearer

**Comment by debseidner** [comment]
That is fine with me but maybe we wait until we do a couple more to see if really an issue? I don't have a strong opinion here, though. I think that language came from the reg attorneys but does not mean we cannot change it.

**Comment by awolfe76** [comment]
:+1: lets give it a bit and see what other(s) think. It's really their, the participants, call.

**Comment by benguhin** [comment]
Sounds good to me
