### ISSUE TITLE
Error message for when the CSV doesn't have the right header row

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#110]
This is a deviation from the thinking in #18 but it could be helpful based on what we noticed in the usability test

Message:
> The header row of your CSV file does not match our [CSV template](http://www.consumerfinance.gov/rural-or-underserved-tool/). Please adjust your CSV file and try again.

**Comment by awolfe76** [comment]
What happened in testing? Just to see what the options might be.

**Comment by benguhin** [comment]
In testing, the tool processed all of the results as "Cannot be identified" with a "null" message for each of the fields. It was confusing and made the system look broken, so it would have been better to not process the CSV and tell the user to fix the header row

**Comment by awolfe76** [comment]
Cool, thanks @benguhin. I have a fix coming soon!
