### ISSUE TITLE
Verbiage changes needed for 12/4 Dodd-Frank amendment

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#116]
Please make the following changes to the verbiage in the QM tool:

- [x]  Remove the second paragraph in "About this tool"

If more than 50 percent of a small creditor’s total first-lien covered transactions in the preceding year or, for certain transactions, the year prior to the preceding year, are secured by properties that are located in areas that are either rural or underserved, a small creditor may be eligible for special provisions and exemptions under certain CFPB regulatory requirements. 

- [x]  In the response to "Q: What does this tool do?", add the last sentence in bold to the response.

A: The tool identifies whether a property is located in a rural or underserved area in a particular calendar year.  Creditors can select a year and enter addresses into the tool, either one at a time or more than one at a time (a “batch upload”), and the tool provides a determination of whether each address is in a rural or underserved area for the year selected.  **You should keep a copy of your results that show the determination for each address run through the tool.**

- [x]  Remove the question "How does the output from the tool help to prove to my regulator that I operated predominantly in rural or underserved areas?" from the FAQs.

- [x]  Remove the part of the sentence in bold from the answer for "Q: How do I interpret the results?"

A: The results will be displayed on a web page after the processing completes in four categories: Rural/Underserved, Not Rural/Underserved, Could Not Be Identified, and Duplicates.  The addresses that return in the Rural/Underserved category will qualify as being in rural or underserved areas.  Those in the Not Rural/Underserved category are addresses that are not in areas designated as rural or underserved.  Addresses in the Could Not Be Identified category will need to be researched further to determine if they are in rural or underserved areas (see “How do I resolve the addresses that could not be identified?” below).  For the Duplicates category, the properties are still counted in one of the three aforementioned categories.  The user must determine which entries are duplicates.  An institution should not count a property more than once **when determining if it operates predominantly in rural or underserved areas** unless more than one first-lien covered transaction was secured by the property in the same year.  

- [x]  Remove the words in bold in the selection below from "Q: How do I resolve the addresses that could not be identified?" Also, please make sure to add in the capital Y to replace the lowercase y you are replacing in "You should check to see..." surrounded by the bold below (in italics) and the word "may" in italics replacing "should" in the second paragraph below the picture.

A: **Before researching the addresses that could not be identified, you should determine whether you can confirm without these addresses that you are operating predominantly in rural or underserved areas – that is, whether more than 50 percent of your total first lien covered transactions were secured by properties located in rural or underserved areas during the preceding calendar year.  Conversely, before researching the addresses that could not be identified, you should consider whether your institution will have more than 50 percent first lien covered transactions secured by properties located in rural or underserved areas if these unidentified addresses are determined to be rural or underserved.  If you find that your institution needs to know if these addresses determine whether your institution operated in predominantly rural or underserved areas,** *y***Y**ou should **then** check to see if the address was mistyped, some information was missing in the address entered, or the address is too new for the tool to return a definite result.  First, verify the address is correct.  If it is correct, try the Census Bureau’s automated address search tool, use the rural or underserved counties lists, or check the form of the address on the United States Postal Service site (https://tools.usps.com/go/ZipLookupAction_input).  For instance, the address 6009 JFK Blvd East, West New York, NJ 07093 cannot be located by the tool.  When the address is entered into the usps.com site, the proper address is given, 6009 Kennedy Blvd E, West New York, NJ 07093-3740, and the address can now be identified in the tool.

PICTURE - leave as is

It is possible that some addresses are too new to appear in the tool, and addresses that could not be identified **should** *may* be attempted again 60, 90 or 120 days later.  **You also have the option to demonstrate that a property is “rural” or “underserved,” as defined in 12 CFR 1026.35(b)(2)(iv)(A) and (B), by other means not covered by the safe harbors.**  If an update or change to an address is required, make the change in your systems of record first, then retry the upload.  For best results, include the street address, city, state and ZIP Code in the batch upload file or your address entry. 

- [x]  Remove the last sentence in bold in the response for "Q: The address that I am checking in the tool is not designated as rural or underserved as I expected.  Why?"

A: The tool designated the address entered as not rural or underserved as those terms are defined in 12 CFR 1026.35(b)(2)(iv)(A) and (B), respectively.  If the address is not designated in the tool as rural or underserved, lenders have the option to check the address on the Census Bureau’s automated address search tool and the rural or underserved counties lists. **Lenders also have the option to demonstrate the property is rural or underserved, as those terms are defined, by other means not covered by the safe harbors.**

 - [x]  Remove the question and answer "How do I calculate from the results whether I qualify as a creditor that operates predominantly in rural or underserved areas?" from the FAQs.

 - [x]  Add the text in italics and remove the text in bold from the explanation under the designated rural or underserved section.

4 addresses are designated as rural or underserved for 2015
First-lien covered transactions extended in 2015 that are secured by these properties can be counted as rural or underserved in your determination of **whether more than 50 percent of** your first-lien covered transactions in 2015 *that* are secured by properties located in rural or underserved areas.  **If your institution meets this more than 50 percent test based on your 2015 loans, you meet the requirement of operating predominantly in rural or underserved areas for purposes of 2016 and for loan applications received before April 1, 2017.**

 - [x]  Add the text in italics and remove the text in bold from the not designated as rural section. Please make sure that cannot is bold in the tool.

11 addresses are not designated as rural or underserved for 2015
These properties **should** *can*not be counted as rural or underserved **in your more than 50 percent test**.

 - [x]  Remove the text in bold from the text under the duplicates section on the tool

3 addresses were identified as duplicates
These addresses have been identified as duplicate entries, and only the first instance of each address has been counted in the other three categories of results.  **Duplicates should not be included in your more than 50 percent test calculation of rural or underserved properties.** 

 - [x]  Remove the last sentence in About the results in bold below.

The tool identifies whether a property is located in a rural or underserved area in a particular year.  **The results delineate which properties can or cannot count toward the more than 50 percent test to determine whether a creditor operated predominantly in rural or underserved areas in a particular year.**

**Comment by debseidner** [comment]
@awolfe76 The verbiage above assumes that #95 has been updated first

**Comment by awolfe76** [comment]
For the change to the `about the results` paragraph, do we even need that section if all it says is:
"The tool identifies whether a property is located in a rural or underserved area in a particular year."

**Comment by debseidner** [comment]
@awolfe76 I agree. We should take it out as that one sentence does not do much and is repeated in three other places.

**Comment by debseidner** [comment]
@awolfe76 Can you also bold the "not" in the following spot?
0
are **not** designated as rural or underserved

**Comment by awolfe76** [comment]
:+1:

**Comment by debseidner** [comment]
changes look good in build environment
