### ISSUE TITLE
Debug issue with new GA script

### ISSUE THREAD

**Issue by awolfe76** [cfpb/rural-or-underserved-test#124]
*See #123 for updates on what is currently in production*

There is a new version of the GA script:
``` HTML
<!-- Google Tag Manager -->
  <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KMMLRS"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-KMMLRS');</script>
<!-- End Google Tag Manager -->
```

However, using this new script causes the download of the dynamically generated results `.csv` file to work incorrectly. Instead of forcing a download it opens a new tab and displays the contents of the `.csv` on the screen. This isn't what we need.

This issue is to track this "bug".

**Comment by awolfe76** [comment]
related to #37

**Comment by wpears** [comment]
So how we can fix this is by generating the link href *before* the true click happens. As long as the user clicks on a static link (ie, they've gotten a chance to see the url) it'll work as expected. I think this is a security measure to prevent weird file bait and switching. I can put a PR in on Monday for this, just need to find the right place in the source to put it.

**Comment by wpears** [comment]
Also, might require a blobURL over just data: but we'll cross that bridge when we get there.

**Comment by awolfe76** [comment]
:+1: 

Doesn't have to be here, but at this point all data will have been loaded and the csv content could be generated (spinner is hidden) - https://github.com/cfpb/rural-or-underserved-test/blob/master/src/js/count.js#L39

Would probably also want to hide the print and download links by default and only show them when ready (show them on the same line as above) - https://github.com/cfpb/rural-or-underserved-test/blob/master/src/index.html#L509
