### ISSUE TITLE
Enable back button to return to the first page

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#128]
In our first two tests, both users assumed that they could use the browser's back button to return to the first page and enter different addresses. 

Currently, clicking back will take you to the whatever you were viewing before you opened the tool. It's not critically important – both participants understood that they needed to click forward to get back to the tool, but it wasn't the expected interaction.

**Comment by debseidner** [comment]
@awolfe76 This is fixed in build as I am not experiencing this issue in build.
