### ISSUE TITLE
Navigation clicks don't go anywhere.

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/rural-or-underserved-test#146]
With Chrome, on a mac, when I visit:

http://www.consumerfinance.gov/rural-or-underserved-tool/

and try to use the site navigation to go to a different page (say, "Notice & Comment"), the URL changes but the page never advances.

**Comment by awolfe76** [comment]
Looking into this now ... any quick ideas @jimmynotjim or @Scotchester?

Also, what version of this is in production currently? Is it master or a release?

**Comment by jimmynotjim** [comment]
@rosskarchner and @anselmbradford is this what you were talking about in Scrum today?

**Comment by anselmbradford** [comment]
No. This is a separate issue.
I was talking about that the cfpb_nemo pages don't have the delay on the menu hover.

**Comment by jimmynotjim** [comment]
Ok, I'll try and dig into this as well

**Comment by Scotchester** [comment]
Pretty weird. The issue seems to be isolated to just these links:

![screen shot 2016-05-02 at 11 54 21](https://cloud.githubusercontent.com/assets/1044670/14959297/aac436c4-105c-11e6-9385-ce39a6e4c9ff.png)

Everything else works for me.

**Comment by jimmynotjim** [comment]
@awolfe76 profiling the click event, it seems that Sammy is taking over click events in the menu, but it's failing to load the page. Unfortunately this bit prevents that error from being logged https://github.com/cfpb/rural-or-underserved-test/blob/be74ce30fb36d175a4d792ee5081ba398db8b62d/src/js/app.js#L115

Any way we can restrict Sammy to just the content of the page? I'm not quite sure how this library works or how we've implemented it.

**Comment by awolfe76** [comment]
Thanks @jimmynotjim. I'll take a look.

**Comment by rosskarchner** [comment]
Any progress on this?

**Comment by awolfe76** [comment]
Should be good. Closing.
