### ISSUE TITLE
Mapbox access token to be disabled

### ISSUE THREAD

**Issue by brianfunk** [cfpb/rural-or-underserved-test#156]
https://github.com/cfpb/rural-or-underserved-test/blob/00abeb6ebc92444013ad70243a10d8dfecd698a2/src/js/showMap.js#L3

@awolfe76 Using Mapbox public key which will soon be disabled.

**Comment by awolfe76** [comment]
Thanks, @brianfunk. Do you have an article/blog post about this and how to move forward?

**Comment by cfarm** [comment]
https://www.mapbox.com/developers/ seems to have the right info. Also, @wpears @contolini have Mapbox experience.

**Comment by brianfunk** [comment]
@awolfe76 This is using a Mapbox public key from an NCI paid Mapbox account.  NCI will be disabling this key.  You can switch to a public key from another account or sign up for a new Mapbox account (https://www.mapbox.com/pricing/).

**Comment by awolfe76** [comment]
Got it! Thanks, @brianfunk.
