### ISSUE TITLE
Addresses that Census cannot Geocode (but others can)

### ISSUE THREAD

**Issue by ericspry** [cfpb/rural-or-underserved-test#21]
I'm finding a number of addresses that return "not found" both on this tool as well as from census.gov directly. These are all rural addresses that geocode on other tools, like google maps. How should we track these? 

Examples: 
6262 Ashton Woods Drive, Moorefield, WV 26836  
288 Settlers Valley Way Lost River, WV 26810 
13286 State Highway 89, Old Station, CA 96071 
5601 Hwy 128, Philo CA 95466

**Comment by awolfe76** [comment]
These are still not found, but closing for now. We have the addresses but the tool functions as it should by putting them in the "not identified" table.
