### ISSUE TITLE
Addresses appearing as rural or underserved but should not be

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#23]
I found a number of addresses that are designated as rural in the tool but should not be. I confirmed that they are not rural in American FactFinder. I also checked the rural and underserved county lists but they are not on there. Please review how they are geocoding in the tool.

3 Giselle Court, Montebello, NY 10901
700 W. Barry Ave. Unit 1W, Chicago, IL 60657
24W737 Argyle Avenue, Roselle, IL 60172-3314

![rural or underserved](https://cloud.githubusercontent.com/assets/9748138/10137358/17fb6fd2-65c7-11e5-9ecc-af636eb9ff75.JPG)

**Comment by awolfe76** [comment]
Ran these on the new tool and they are not rural.
