### ISSUE TITLE
Change downloaded file to have a CSV extension

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#37]
The way the download results works today, the file is not downloaded as a CSV. It does not have an extension so it is not recognized by a program. Instead, you have to choose a program and then if you choose excel, you have to parse the file. Please enhance this to download as a .CSV extension.

![doesn t recognize download](https://cloud.githubusercontent.com/assets/9748138/10552118/9591cf2a-741f-11e5-87d5-764b83943f02.JPG)

**Comment by awolfe76** [comment]
@debseidner - does this still happen? If yes, can you tell me what browser?

**Comment by debseidner** [comment]
@awolfe76 Yes, this is still happening in both chrome and firefox on windows.

**Comment by awolfe76** [comment]
In PR #129 I had to remove this fix. The GTM snippet caused the fix to open a new window and display the csv contents in the browser rather than downloading the csv file.

**Comment by awolfe76** [comment]
related to #124
