### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by mebates** [cfpb/rural-or-underserved-test#41]
@benguhin asked me to review the tool to create a prioritized list of design improvements. Happy to talk through each one if they're not clear. @awolfe76 do you have Ben's wireframe .ai file?

**Top priority**
- [x] Add current cf.gov navigation; grab code from OaH (or there might be a repo specifically for this nav, ask Adam Scott)
- [x] Title “Rural and underserved areas automated tool” will move below nav as H1, match spacing on this page: http://beta.consumerfinance.gov/activity-log/
- [x] Add current cf.gov global footer
- [x] Build out expand/collapse for FAQs. Match this page: http://beta.consumerfinance.gov/contact-us/ (I assume you're working on this!)

**Bigger pattern changes**
- [x] Per Ben’s wireframe, move “Look up addresses” button outside of gray box (see #43)
  - include max file size? ‘choose file’ as secondary buttons style? excel template?
- [x] Add breadcrumbs (see #44)
- [x] Adjust words and buttons on Results page to match Ben’s wireframe
  - Clearer sentence introducing results, buttons become links, sitting below. 
- [x] Add stronger lines separating sections on Results page

**Smaller style/standards fixes**
- [x] Link style needs dotted underline
- [x] Button type size is correct, but it needs more padding so the button is bigger
- [x] Address input style should match V1 input style: no fuzz on focus, thicker line, hard corners
- [x] Adjust grid to match V1 / Capital Framework grid (it is too narrow right now)
- [x] Table header rows should be H5 type style

**Open questions**
- Are we including error states?
- Can you sort the tables?

**Comment by mebates** [comment]
@awolfe76 I just turned off my notifications for this repo cause you seem to be working like lightning! I'm wondering where I can see the latest, just to check all of these design improvements? Thanks!

**Comment by mebates** [comment]
Thanks for the link! I have no idea if you have time to make changes, but here's what I see:

*Top priority*
- [ ] There is something funky going on with the navigation - titles on the dropdowns should not be in all caps (looks like the H5 style to me)

*Fussy*
- [ ] The corner radius on the buttons is too sharp (are you using Capital Framework?)
- [ ] Can we add a space after 'in' and the year dropdown? It looks weird with no space
- [ ] Can we increase the right margin on the right gray box ("Enter addresses Manually") so it's even with the other margins and potentially forces "10" down to the second line?
- [ ] Can the rule around the gray boxes be thinner?
- [ ] Add more space between 'Related tools' and 'Related links' chunks in the sidebar
- [ ] Add more space between "Questions on the tool" and "Frequently asked questions". I didn't realize you were starting a category until I scrolled down; it just seemed redundant. 
- [ ] Add download minicon after "Download CSV template" (should be blue) on main page
- [ ] On results page, the download minicon should be blue not gray

cc: @benguhin

**Comment by awolfe76** [comment]
Thanks @mebates. Going to pull these out into a new issue.
