### ISSUE TITLE
Usability Testing

### ISSUE THREAD

**Issue by lesgou** [cfpb/rural-or-underserved-test#42]
We will be conducting soft launch testing for Cricket in the month of December to see how user friendly the QM tool is to banks.
https://github.com/cfpb/rural-or-underserved-test
-  [x] Working with Markets to identify banks for testing
-  [x] Working with EA to identify banks for testing
-  [ ] Testing with community banks
-  [ ] Testing with credit unions
-  [ ] Update FAQs based on testing

**Comment by awolfe76** [comment]
@benguhin @debseidner - can we close this issue?

**Comment by debseidner** [comment]
@awolfe76 Technically we are still conducting the testing. We'll have one tomorrow. I saw a bank wrote Friday that they would like to meet. After that, I can close this out.
