### ISSUE TITLE
Text in boxes on landing page run together in IE10

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#58]
The words run together and are out of the box in the address select boxes in IE for both versions of the tool. We should fix this so the design appears better on the site in IE.

Note: The functionality is working fine in IE so this is only a design/look issue.

Mapbox backend:

![ie mapbox](https://cloud.githubusercontent.com/assets/9748138/10972999/aa3f5692-83a9-11e5-97cf-5eeceeb608a7.JPG)

Census backend:
![ie census](https://cloud.githubusercontent.com/assets/9748138/10973016/b795f2ba-83a9-11e5-8f9f-bc44b62d469b.JPG)

**Comment by benguhin** [comment]
This is the primary design issue in IE10
