### ISSUE TITLE
Include all columns of information in duplicates section

### ISSUE THREAD

**Issue by benguhin** [cfpb/rural-or-underserved-test#66]
Coming out of #45, I think we should allow identical addresses with different apartment numbers to be listed as duplicates for the Jan 1 release. The issue should solve itself when we move away from the Census API, and it's not a huge issue for the purposes of this tool.

That said, I think we should make two adjustments so that it's clearer that a duplicate *might* actually be a unique property:

- [x] Include the address identified, county, census block, and rural yes/no for the duplicate results so that a lender can use that information in their calculations
- [x] Adjust the intro text above the duplicate results section 

-
---

Adjusted text:  
The tool identified these properties as duplicate entries. An address appears in the duplicate count because there is more than one identical address in your CSV file. Duplicates should not be included in your more than 50 percent test calculation of rural or underserved properties. 

Image of track changes (I just removed content):
![screen shot 2015-11-06 at 11 37 45 am](https://cloud.githubusercontent.com/assets/6953063/11002473/ebcfd1a0-847a-11e5-89df-8bee5b19e119.png)

**Comment by awolfe76** [comment]
Closing for now. Can reopen later if necessary.

We currently don't have the info to display, we aren't making the API call for duplicates.
