### ISSUE TITLE
Add in CSV creation instructions into the CSV FAQ

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#83]
Please replace the response to the following FAQ with the information in the attached document.

Q: What is CSV?

The new response can be found here:

https://docs.google.com/a/cfpb.gov/document/d/1GfzrpqNHGu31G2V-TEV0hL37zj8meF2_LcoT23ZyFsU/edit?usp=sharing

**Comment by awolfe76** [comment]
have this one complete. will make the PR soon.
