### ISSUE TITLE
MapBox hangs on files and does not complete

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#84]
Files with addresses from PR and US VI do not finish when tested on the MapBox site. They hang in the middle and even after a half an hour, do not finish.

Test files (VI.csv and PR.csv) are located on google drive in HMDA --> Qualified Mortgage Rural Checker --> TestData --> State Data.

Here is where the US VI file got stuck.
![vi stuck](https://cloud.githubusercontent.com/assets/9748138/11510303/13dc7d46-9831-11e5-8d40-c507f7407a25.JPG)

**Comment by debseidner** [comment]
Kentucky hangs on this address and will not finish: 700 TERMINAL AVE, LIBERAL, KS 67901

**Comment by awolfe76** [comment]
Going to close this for now. If mapbox comes back up we can reopen.
