### ISSUE TITLE
Display an error message for the uploaded file being in the incorrect format

### ISSUE THREAD

**Issue by debseidner** [cfpb/rural-or-underserved-test#96]
We should display an error message if the batch file trying to be checked in the tool is not a CSV file. The error message should display when the user selects a file and clicks "check addresses".

**Comment by debseidner** [comment]
@benguhin Not sure what the error message should say but maybe "The file uploaded is not a CSV. Please reformat using the provided template and try again." Please let us know your thoughts on what it should say.

**Comment by awolfe76** [comment]
I have this working locally, just need the content for the message. :+1:

**Comment by benguhin** [comment]
How about this:

> The file uploaded is not a CSV file. This tool can only process CSV files that use our [CSV template](http://www.consumerfinance.gov/rural-or-underserved-tool/csv-template.csv). For more information about CSV files, view our Frequently Asked Questions below.

**Comment by benguhin** [comment]
This is better:

> The file uploaded is not a CSV file. Please try again with a CSV file that uses our [CSV template](http://www.consumerfinance.gov/rural-or-underserved-tool/csv-template.csv). For more information about CSV files, view our Frequently Asked Questions below.

**Comment by benguhin** [comment]
This is better:

> The file uploaded is not a CSV file. Please try again with a CSV file that uses our [CSV template](http://www.consumerfinance.gov/rural-or-underserved-tool/csv-template.csv). For more information about CSV files, view our Frequently Asked Questions below.

**Comment by awolfe76** [comment]
Got it. Thanks.
